spring.application.name=ecom-application
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test

#if use .yml file
#spring:
#    application:
#        name: ecom-accplication
#    h2:
#        console:
#            enabled: true
#    datasource:
#        url: jdbc:h2:mem:test